export const UPDATE_CURRENT_WEATHER = 'UPDATE_CURRENT_WEATHER';

export const SWITCH_SYSTEM = 'SWITCH_SYSTEM';
export const SWITCH_TEMPERATURE_UNITS = 'SWITCH_TEMPERATURE_UNITS';
export const SWITCH_PRESSURE_UNITS = 'SWITCH_PRESSURE_UNITS';
